# H2
spring:
  h2: # enable web ui console located at localhost:8080/h2 - use the URL beneath to connect to the same DB
    console:
      enabled: true
      path: /h2
# Datasource
  datasource:
    # change the file path OR use memory only, e.g. jdbc:h2:mem:<databaseName>
    url: jdbc:h2:file:/tmp/rest-example/h2
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update